const fs = require('fs');
const path = require('path');

const base = __dirname;
const BT = '`';
const DS = '$';

// Create directories
fs.mkdirSync(path.join(base, 'lib'), { recursive: true });
fs.mkdirSync(path.join(base, 'pages', 'api'), { recursive: true });
console.log('Directories created.');

// --- lib/scamKeywords.js ---
fs.writeFileSync(path.join(base, 'lib', 'scamKeywords.js'), [
  'const scamKeywords = [',
  '  { keyword: "registration fee", weight: 20, reason: "Registration fee detected" },',
  '  { keyword: "processing fee", weight: 20, reason: "Processing fee detected" },',
  '  { keyword: "security deposit", weight: 18, reason: "Security deposit request detected" },',
  '  { keyword: "pay to join", weight: 22, reason: "Pay-to-join scheme detected" },',
  '  { keyword: "payment required", weight: 20, reason: "Upfront payment required" },',
  '  { keyword: "fee", weight: 10, reason: "Monetary fee mentioned" },',
  '  { keyword: "\u20b9", weight: 5, reason: "Currency amount mentioned in context of fees" },',
  '  { keyword: "pay \u20b9", weight: 18, reason: "Direct payment request detected" },',
  '  { keyword: "bank transfer", weight: 12, reason: "Bank transfer request detected" },',
  '  { keyword: "upi", weight: 8, reason: "UPI payment method mentioned" },',
  '  { keyword: "guaranteed placement", weight: 18, reason: "Unrealistic guarantee of job" },',
  '  { keyword: "100% placement", weight: 20, reason: "Unrealistic 100% placement guarantee" },',
  '  { keyword: "guaranteed job", weight: 18, reason: "Unrealistic guarantee of job" },',
  '  { keyword: "earn from day 1", weight: 15, reason: "Unrealistic earning promise" },',
  '  { keyword: "earn while you learn", weight: 8, reason: "Potentially misleading earning claim" },',
  '  { keyword: "no experience required", weight: 6, reason: "No-experience claim may be a red flag" },',
  '  { keyword: "no skills needed", weight: 12, reason: "No-skills-needed claim is suspicious" },',
  '  { keyword: "immediate joining", weight: 8, reason: "Urgency tactic detected" },',
  '  { keyword: "limited seats", weight: 14, reason: "Artificial scarcity / urgency tactic" },',
  '  { keyword: "hurry", weight: 10, reason: "Urgency pressure tactic detected" },',
  '  { keyword: "last date", weight: 6, reason: "Deadline pressure tactic" },',
  '  { keyword: "confirm your seat", weight: 14, reason: "Seat-confirmation pressure tactic" },',
  '  { keyword: "apply now", weight: 4, reason: "Urgency language detected" },',
  '  { keyword: "offer expires", weight: 14, reason: "Expiration urgency tactic" },',
  '  { keyword: "act fast", weight: 12, reason: "High-pressure urgency tactic" },',
  '  { keyword: "whatsapp", weight: 10, reason: "Communication via WhatsApp instead of official channels" },',
  '  { keyword: "telegram", weight: 10, reason: "Communication via Telegram instead of official channels" },',
  '  { keyword: "dm us", weight: 10, reason: "Informal communication channel" },',
  '  { keyword: "personal email", weight: 8, reason: "Personal email used instead of corporate" },',
  '  { keyword: "gmail.com", weight: 6, reason: "Free email provider used for recruitment" },',
  '  { keyword: "yahoo.com", weight: 6, reason: "Free email provider used for recruitment" },',
  '  { keyword: "work from home", weight: 4, reason: "Work-from-home claim (context-dependent)" },',
  '  { keyword: "certificate provided", weight: 3, reason: "Certificate claim (common in paid scams)" },',
  '  { keyword: "stipend after training", weight: 10, reason: "Delayed stipend after unpaid training period" },',
  '  { keyword: "training period unpaid", weight: 14, reason: "Unpaid training period is a red flag" },',
  '];',
  '',
  'module.exports = scamKeywords;',
  ''
].join('\n'));
console.log('Created lib/scamKeywords.js');

// --- lib/riskCalculator.js ---
fs.writeFileSync(path.join(base, 'lib', 'riskCalculator.js'), [
  'const scamKeywords = require("./scamKeywords");',
  '',
  'function keywordScan(text) {',
  '  const lower = text.toLowerCase();',
  '  const matched = [];',
  '  let score = 0;',
  '',
  '  for (const entry of scamKeywords) {',
  '    if (lower.includes(entry.keyword)) {',
  '      score += entry.weight;',
  '      matched.push(entry.reason);',
  '    }',
  '  }',
  '',
  '  return { score, reasons: [...new Set(matched)] };',
  '}',
  '',
  'function calculateRisk(keywordResult, aiResult) {',
  '  const kwScore = Math.min(keywordResult.score, 100);',
  '  const aiScore =',
  '    typeof aiResult.riskScore === "number"',
  '      ? Math.min(Math.max(aiResult.riskScore, 0), 100)',
  '      : 0;',
  '',
  '  const combined = Math.round(kwScore * 0.4 + aiScore * 0.6);',
  '  const finalScore = Math.min(combined, 100);',
  '',
  '  const aiReasons = Array.isArray(aiResult.reasons) ? aiResult.reasons : [];',
  '  const allReasons = [...new Set([...aiReasons, ...keywordResult.reasons])];',
  '',
  '  let status;',
  '  if (finalScore >= 70) status = "High Risk";',
  '  else if (finalScore >= 40) status = "Medium Risk";',
  '  else status = "Low Risk";',
  '',
  '  return { riskScore: finalScore, status, reasons: allReasons };',
  '}',
  '',
  'module.exports = { keywordScan, calculateRisk };',
  ''
].join('\n'));
console.log('Created lib/riskCalculator.js');

// --- lib/grokService.js ---
fs.writeFileSync(path.join(base, 'lib', 'grokService.js'), [
  'const GROK_API_URL = "https://api.x.ai/v1/chat/completions";',
  '',
  'async function analyzeWithGrok(text) {',
  '  const apiKey = process.env.GROK_API_KEY;',
  '  if (!apiKey || apiKey === "your_grok_api_key") {',
  '    throw new Error("GROK_API_KEY is not configured");',
  '  }',
  '',
  '  const systemPrompt = ' + BT + 'You are a scam detection expert specializing in fake internship postings. When given an internship description, analyze it for scam indicators and return ONLY valid JSON in this exact format (no markdown, no code fences):',
  '{',
  '  "riskScore": <number 0-100>,',
  '  "reasons": ["reason1", "reason2"],',
  '  "summary": "brief summary"',
  '}',
  '',
  'Look for these scam signals:',
  '- Requests for payment, registration fees, or deposits',
  '- Unrealistic promises (guaranteed placement, high salary for no experience)',
  '- Pressure tactics (limited seats, act fast, offer expires)',
  '- Informal communication channels (WhatsApp, Telegram, personal email)',
  '- Vague company details or no verifiable company information',
  '- Grammar/spelling issues typical of scam postings',
  '- Too-good-to-be-true offers' + BT + ';',
  '',
  '  const response = await fetch(GROK_API_URL, {',
  '    method: "POST",',
  '    headers: {',
  '      Authorization: ' + BT + 'Bearer ' + DS + '{apiKey}' + BT + ',',
  '      "Content-Type": "application/json",',
  '    },',
  '    body: JSON.stringify({',
  '      model: "grok-3-mini",',
  '      messages: [',
  '        { role: "system", content: systemPrompt },',
  '        {',
  '          role: "user",',
  '          content: ' + BT + 'Analyze the following internship description and identify possible scam indicators such as payment requests, unrealistic promises, or suspicious wording. Return structured JSON.\\n\\nInternship Description:\\n' + DS + '{text}' + BT + ',',
  '        },',
  '      ],',
  '      temperature: 0.3,',
  '    }),',
  '    signal: AbortSignal.timeout(30000),',
  '  });',
  '',
  '  const data = await response.json();',
  '  const content = data.choices?.[0]?.message?.content;',
  '  if (!content) {',
  '    throw new Error("Empty response from Grok API");',
  '  }',
  '',
  '  const cleaned = content.replace(/' + BT + BT + BT + '(?:json)?\\s*/g, "").replace(/' + BT + BT + BT + '/g, "").trim();',
  '  const parsed = JSON.parse(cleaned);',
  '',
  '  return {',
  '    riskScore: typeof parsed.riskScore === "number" ? parsed.riskScore : 0,',
  '    reasons: Array.isArray(parsed.reasons) ? parsed.reasons : [],',
  '    summary: parsed.summary || "",',
  '  };',
  '}',
  '',
  'module.exports = { analyzeWithGrok };',
  ''
].join('\n'));
console.log('Created lib/grokService.js');

// --- lib/scamAnalyzer.js ---
fs.writeFileSync(path.join(base, 'lib', 'scamAnalyzer.js'), [
  'const { analyzeWithGrok } = require("./grokService");',
  'const { keywordScan, calculateRisk } = require("./riskCalculator");',
  '',
  'async function fetchTextFromUrl(url) {',
  '  const response = await fetch(url, {',
  '    headers: {',
  '      "User-Agent":',
  '        "Mozilla/5.0 (compatible; FakeInternshipDetector/1.0; +https://github.com)",',
  '    },',
  '    signal: AbortSignal.timeout(15000),',
  '  });',
  '',
  '  const html = await response.text();',
  '',
  '  const text = html',
  '    .replace(/<script[\\s\\S]*?<\\/script>/gi, "")',
  '    .replace(/<style[\\s\\S]*?<\\/style>/gi, "")',
  '    .replace(/<[^>]+>/g, " ")',
  '    .replace(/&amp;/g, "&")',
  '    .replace(/&lt;/g, "<")',
  '    .replace(/&gt;/g, ">")',
  '    .replace(/&quot;/g, \'"\') ',
  '    .replace(/&#39;/g, "\'")',
  '    .replace(/&nbsp;/g, " ")',
  '    .replace(/\\s+/g, " ")',
  '    .trim();',
  '',
  '  if (!text) {',
  '    throw new Error("Could not extract text content from the provided URL");',
  '  }',
  '',
  '  return text.slice(0, 4000);',
  '}',
  '',
  'async function analyzeInternship({ text, url }) {',
  '  let content = text;',
  '  if (!content && url) {',
  '    content = await fetchTextFromUrl(url);',
  '  }',
  '',
  '  if (!content || content.trim().length === 0) {',
  '    throw new Error("No internship text or URL provided for analysis");',
  '  }',
  '',
  '  const keywordResult = keywordScan(content);',
  '',
  '  let aiResult = { riskScore: 0, reasons: [], summary: "" };',
  '  try {',
  '    aiResult = await analyzeWithGrok(content);',
  '  } catch (err) {',
  '    console.error("Grok API analysis failed, falling back to keyword-only:", err.message);',
  '    return {',
  '      riskScore: Math.min(keywordResult.score, 100),',
  '      status:',
  '        keywordResult.score >= 70',
  '          ? "High Risk"',
  '          : keywordResult.score >= 40',
  '          ? "Medium Risk"',
  '          : "Low Risk",',
  '      reasons: keywordResult.reasons,',
  '      aiAvailable: false,',
  '    };',
  '  }',
  '',
  '  const result = calculateRisk(keywordResult, aiResult);',
  '  result.aiAvailable = true;',
  '  if (aiResult.summary) result.summary = aiResult.summary;',
  '',
  '  return result;',
  '}',
  '',
  'module.exports = { analyzeInternship, fetchTextFromUrl };',
  ''
].join('\n'));
console.log('Created lib/scamAnalyzer.js');

// --- pages/api/analyze.js ---
fs.writeFileSync(path.join(base, 'pages', 'api', 'analyze.js'), [
  'const { analyzeInternship } = require("../../lib/scamAnalyzer");',
  '',
  'export default async function handler(req, res) {',
  '  if (req.method !== "POST") {',
  '    return res.status(405).json({ error: "Method not allowed" });',
  '  }',
  '',
  '  try {',
  '    const { text, url } = req.body;',
  '',
  '    if (!text && !url) {',
  '      return res.status(400).json({',
  '        error: "Request must include either \'text\' or \'url\' field",',
  '      });',
  '    }',
  '',
  '    if (url && !/^https?:\\/\\/.+/i.test(url)) {',
  '      return res.status(400).json({',
  '        error: "Invalid URL format. Must start with http:// or https://",',
  '      });',
  '    }',
  '',
  '    const result = await analyzeInternship({ text, url });',
  '    return res.status(200).json(result);',
  '  } catch (err) {',
  '    console.error("Analysis error:", err.message);',
  '    return res.status(500).json({',
  '      error: "Analysis failed",',
  '      message: err.message,',
  '    });',
  '  }',
  '}',
  ''
].join('\n'));
console.log('Created pages/api/analyze.js');

console.log('\nAll files created successfully!');
console.log('You can now delete _mkdirs.js, _mkdirs.bat, and create_dirs.py');
